import { apiSlice } from "./apiSlice";


const USERS_URL = `${process.env.REACT_APP_API}/users`
const SUPERDISTRIBUTOR_LIST = `${process.env.REACT_APP_API}/superdistributor`
const DISTRIBUTOR_LIST = `${process.env.REACT_APP_API}/distributor`
const RETAILER_LIST = `${process.env.REACT_APP_API}/retailer`
const DASHBOARD = `${process.env.REACT_APP_API}/dashboard`
const PAYMENTS = `${process.env.REACT_APP_API}/payments`
const RAZOR = `${process.env.REACT_APP_API}/razor`
const CASHFREE = `${process.env.REACT_APP_API}/cashfree`
const Contact = `${process.env.REACT_APP_API}/contact`
const Services = `${process.env.REACT_APP_API}/services`
const Utilities = `${process.env.REACT_APP_API}/utilities`
const GST = `${process.env.REACT_APP_API}/gst`
const PHONEPE = `${process.env.REACT_APP_API}/phonepe`
const REPORTER = `${process.env.REACT_APP_API}/reporter`
export const usersApiSlice = apiSlice.injectEndpoints({
    endpoints:(builder)=>({
        dashboard:builder.mutation({
            query:(data)=>({
                    url:`${DASHBOARD}/`,
                    method:"POST",
                    body:data
            })
        }),
        login:builder.mutation({
            query:(data)=>({
                    url:`${USERS_URL}/auth`,
                    method:"POST",
                    body:data
            })
        }),
        accepTerms:builder.mutation({
            query:()=>({
                url:`${USERS_URL}/terms`,
                method:'PUT',

            })
        }),
        logout:builder.mutation({
            query:()=>({
                url:`${USERS_URL}/logout`,
                method:"POST",

            })
        }),
        updateUser:builder.mutation({
            query:(data)=>({
                url:`${USERS_URL}/profile`,
                method:'PUT',
                body:data
            })
        }),
        getUser:builder.query({
            query:()=>({
                url:`${USERS_URL}/profile`,
                method:'GET'
            })
        }),
        createUser:builder.mutation({
            query:(data)=>({
                url:`${USERS_URL}/`,
                method:'POST',
                body:data
            })
        }),
        getSuperDistributor:builder.mutation({
            query:()=>({
                url:`${SUPERDISTRIBUTOR_LIST}/profile`,
                method:'GET',
            })
        }),
        createSuperDistributor:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/register`,
                method:'POST',
                body:data
            })
        }),
        getSuperDistributorDetails:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/profile/id`,
                method:'POST',
                body:data
            })
        }),
        updateSuperDistributorMargin:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/update`,
                method:'PUT',
                body:data
            })
        }),
        updateSuperDistributor:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/profile`,
                method:'PUT',
                body:data
            })
        }),
        approveSuperDistributor:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/approve`,
                method:'POST',
                body:data
            })
        }),
        activateSuperDistributor:builder.mutation({
            query:(data)=>({
                url:`${SUPERDISTRIBUTOR_LIST}/status`,
                method:'PUT',
                body:data
            })
        }),
        getDistributor:builder.mutation({
            query:()=>({
                url:`${DISTRIBUTOR_LIST}/profile`,
                method:'GET',
            })
        }),
        createDistributor:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/register`,
                method:'POST',
                body:data
            })
        }),
        getDistributorDetails:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/profile/id`,
                method:'POST',
                body:data
            })
        }),
        updateDistributorMargin:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/update`,
                method:'PUT',
                body:data
            })
        }),
        updateDistributor:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/profile`,
                method:'PUT',
                body:data
            })
        }),
        approveDistributor:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/approve`,
                method:'POST',
                body:data
            })
        }),
        activateDistributor:builder.mutation({
            query:(data)=>({
                url:`${DISTRIBUTOR_LIST}/status`,
                method:'PUT',
                body:data
            })
        }),
        createRetailer:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/register`,
                method:'POST',
                body:data
            })
        }),
        getRetailer:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/profile`,
                method:'POST',
                body:data
            })
        }),
        getRetailerDetails:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/profile/id`,
                method:'POST',
                body:data
            })
        }),

        updateRetailer:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/profile`,
                method:'PUT',
                body:data
            })
        }),
        approveRetailer:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/approve`,
                method:'POST',
                body:data
            })
        }),
        updateRetailerPercentage:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/update`,
                method:'PUT',
                body:data,
            })
        }),
        activeRetailer:builder.mutation({
            query:(data)=>({
                url:`${RETAILER_LIST}/status`,
                method:'PUT',
                body:data
            })
        }),
        createOrder:builder.mutation({
            query:(data)=>({
                url:`${PAYMENTS}`,
                method:"POST",
                body:data
            })
        }),
        orderStatus:builder.mutation({
            query:(data)=>({
                url:`${RAZOR}/payment-status`,
                method:'POST',
                body:data
            })
        }),
        createRazorOrder:builder.mutation({
            query:(data)=>({
                url:`${RAZOR}`,
                method:'POST',
                body:data
            })
        }),
        orderHistory:builder.mutation({
            query:(data)=>({
                url:`${PAYMENTS}/orders`,
                method:'POST',
                body:data
            })
        }),
        retailer:builder.mutation({
            query:(data)=>({
                url:`${DASHBOARD}/retailer`,
                method:'POST',
                body:data
            })
        }),
        aadhar:builder.mutation({
            query:(data)=>({
                url:`${CASHFREE}/verify-aadhar`,
                method:'POST',
                body:data
            })
        }),
        otp:builder.mutation({
            query:(data)=>({
                url:`${CASHFREE}/verify-otp`,
                method:'POST',
                body:data
            })
        }),
        pan:builder.mutation({
            query:(data)=>({
                url:`${CASHFREE}/verify-pan`,
                method:'POST',
                body:data
            })
        }),
        contact:builder.mutation({
            query:(data)=>({
                url:`${Contact}/`,
                method:'POST',
                body:data
            })
        }),
        forgotPassword:builder.mutation({
            query:(data)=>({
                url:`${Services}/forgot-password`,
                method:'POST',
                body:data
            })
        }),
        verify:builder.mutation({
            query:(data)=>({
                url:`${Services}/verify`,
                method:'POST',
                body:data
            })
        }),
        resetPassword:builder.mutation({
            query:(data)=>({
                url:`${Services}/reset-password`,
                method:'POST',
                body:data
            })
        }),
        category:builder.mutation({
            query:()=>({
                url:`${Utilities}`,
                method:'GET',
            })
        }),
        biller:builder.mutation({
            query:(data)=>({
                url:`${Utilities}/biller`,
                method:'POST',
                body:data
            })
        }),
        billerDetails:builder.mutation({
            query:(data)=>({
                url:`${Utilities}/billerDetails`,
                method:'POST',
                body:data
            })
        }),
        billerEnquiry:builder.mutation({
            query:(data)=>({
                url:`${Utilities}/billerEnquiry`,
                method:'POST',
                body:data
            })
        }),
        billerPayment:builder.mutation({
            query:(data)=>({
                url:`${Utilities}/billPayment`,
                method:'POST',
                body:data
            })
        }),
        gst:builder.mutation({
            query:(data)=>({
                url:`${GST}`,
                method:'POST',
                body:data
            })
        }),
        phonepe:builder.mutation({
            query:(data)=>({
                url:`${PHONEPE}`,
                method:'POST',
                body:data
            })
        }),
        getReporter:builder.mutation({
            query:()=>({
                url:`${REPORTER}/profile`,
                method:'GET'
            })
        }),
        createReporter:builder.mutation({
            query:(data)=>({
                url:`${REPORTER}/register`,
                method:"POST",
                body:data
            })
        })
    })
})

export const{useDashboardMutation,useLoginMutation,useAccepTermsMutation,useLogoutMutation,useUpdateUserMutation,useGetUserQuery,useCreateUserMutation,useGetDistributorMutation,useCreateDistributorMutation,useGetDistributorDetailsMutation,useUpdateDistributorMarginMutation,useUpdateDistributorMutation,useActivateDistributorMutation,useGetRetailerMutation,useCreateRetailerMutation,useApproveDistributorMutation,useGetRetailerDetailsMutation,useUpdateRetailerMutation,useApproveRetailerMutation,useUpdateRetailerPercentageMutation,useActiveRetailerMutation,useCreateOrderMutation,useOrderStatusMutation,useCreateRazorOrderMutation,useOrderHistoryMutation,useRetailerMutation,useAadharMutation,useOtpMutation,usePanMutation,useContactMutation,useForgotPasswordMutation,useVerifyMutation,useResetPasswordMutation,useCategoryMutation,useBillerMutation,useBillerDetailsMutation,useBillerEnquiryMutation,useBillerPaymentMutation,useGstMutation,usePhonepeMutation,useGetSuperDistributorMutation,useCreateSuperDistributorMutation,useGetSuperDistributorDetailsMutation,useUpdateSuperDistributorMarginMutation,useUpdateSuperDistributorMutation,useActivateSuperDistributorMutation,useApproveSuperDistributorMutation,useGetReporterMutation,useCreateReporterMutation} = usersApiSlice
